// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn_qLYfHYuRkDixcsFI_vcTt7sBFKo0U4',
    appId: '1:858092692119:web:d13d3d6f65af32e8973fd2',
    messagingSenderId: '858092692119',
    projectId: 'foodshareconnect-d9939',
    authDomain: 'foodshareconnect-d9939.firebaseapp.com',
    storageBucket: 'foodshareconnect-d9939.appspot.com',
    measurementId: 'G-GBKY0YT0NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6JDhLzZMUiUNXtNRv-9WG4ijJVzNa3rA',
    appId: '1:858092692119:android:dbe14e20a72114de973fd2',
    messagingSenderId: '858092692119',
    projectId: 'foodshareconnect-d9939',
    storageBucket: 'foodshareconnect-d9939.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxAQAKqCuCdNkzN3N-n-RXyQDaz0be8WI',
    appId: '1:858092692119:ios:18a1397e0e956dda973fd2',
    messagingSenderId: '858092692119',
    projectId: 'foodshareconnect-d9939',
    storageBucket: 'foodshareconnect-d9939.appspot.com',
    iosBundleId: 'com.example.ngoDonorApp',
  );
}